### ISSUE TITLE
Fresh install error (new: command not found)

### ISSUE THREAD

**Issue by grf1** [stolinski/drop-in#17]
<img width="298" alt="Screenshot 2024-05-05 at 21 42 54" src="https://github.com/stolinski/drop-in/assets/4109420/65b7e86f-8d69-45ce-8d00-81a88f7a91bc">

Just trying to follow the README and I'm running into this, I may be missing something but unfortunately lack the skills to troubleshoot further...

**Comment by stolinski** [comment]
<img width="974" alt="Screenshot 2024-05-07 at 11 51 48 AM" src="https://github.com/stolinski/drop-in/assets/669383/1d2dc4aa-f2c9-4f4a-9412-47c8762658b3">

Interesting. I'll have to try this on other machines. Make sure there are no spaces there, I tried copying mine right from the read me and it worked

**Comment by grf1** [comment]
My bad.... so obvious now it's embarrassing. I needed to change into the templates/base directory :)
